@startuml "Empleados"

class Empresa {
    {static} - PORC_ADIC_2_A_5_ANIOS number
    {static} - PORC_ADIC_MAS_DE_5_ANIOS number

    + getSalarios():number
    + empleadoConMasClientes():Empleado

}

abstract class Empleado {
    - DNI:string 
    - nombres:string
    - apellidos:string
    - fechaIngreso:Date 

    + getSalario():number


}

class EmpleadoSalarioFijo {
    - sueldoBasico:number

    + getSalario():number
    
}

class EmpleadosComision {
    - salarioMinimo:number
    - numeroClientesCaptados:number
    - montoPorClienteCaptado:number

    + getSalario():number
}

Empleado <-- Empresa
EmpleadoSalarioFijo <|-- Empleado
EmpleadosComision <|-- Empleado


@enduml