@startuml "La biblioteca"

class Libro {
    # ISBN:string
    # nombreLibro:string
    # editorial:string
    # anio:number
    # autor:Autor
    # tipoLibro: TipoLibro

    getISBN(): string
    getNombreLibro(): string

}

enum TipoLibro {
    NOVELA,
    TEATRO,
    POESIA,
    ENSAYO
}

class Autor {
    - nombreAutor:string
    - nacionalidad:string
    - fechaNacimiento:string
}

class Copia extends Libro {
    - idCopia:string
    - estatusCopia:EstatusCopia
    + cambiarEstatusCopia(EstatusCopia):void
    + crearCopia(Libro):void
    + getIdCopia(): string
    + getEstatusCopia(): string 
}

enum EstatusCopia {
    EN_BIBLIOTECA,
    PRESTADA,
    CON_RETRASO,
    EN_REPARACION
}

class Biblioteca {

    - NUMERO_MAX_PRESTAMOS:number
    - NUMERO_MAX_DIAS:number
    - DIAS_DE_MULTA:number
    - NUMERO_MAX_COPIAS:number

    + nombreBiblioteca:string

    - copias[]:Copia
    - prestamos[]:Prestamo
    - lectores[]:Lector
    - devolverLibro(Prestamo):string{}
    - calcularDiasDePrestamo():number
    - calcularMulta():number

    + agregarLector(Lector):string{}
    + crearCopias(Libro):Copia
    + traerCopias():Copia[]
    - buscarLectorPorId(string):Lector
    - buscarCopiaPorId(string):Copia
    + prestarLibro(string, string):ResponseMessage
    + mostrarPrestamos(): Prestamos[]
    + devolverLibro(idCopia:string): ResponseMessage 
    + repararCopia(idCopia: string): ResponseMessage
    + mostrarRegistros(): void
    + buscarPrestamoPorId(string):Prestamo
}

class Persona {
    # idPersona: string
    # nombresApellidos: string
    # edad: number

    + getIdPersona():string
    + getNombresApellidos():string
}

class Lector extends Persona{
    - estaSolvente: boolean
    - registros:Registros[]
    - _numeroCopias: number;

    + numeroCopias(): number
    + actualizarNumeroCopias(number)

}

class Prestamo {
    - idPrestamo:string
    - lector:Lector
    - copia:Copia
    - fechaPrestamo:Date
    - fechaDevolucion:Date

    + idGenerator(string):string
}

TipoLibro <-- Libro: "Es de tipo"
Autor "1" <-- "1" Libro: "ha sido escrito por"
EstatusCopia "1" <-- "1" Copia: "tiene"
Biblioteca "1" *-- "1..*" Lector: "congrega a"
Biblioteca "1" *-- "1..*" Copia: "se compone de"
Biblioteca "1" *-- "1..*" Prestamo: "se compone de"

@enduml